version: "3"
services:
  web:
    image: nginx
    expose:
      - "80"
    volumes:
      - ./dist:/usr/share/nginx/html  # Pointer vers le dossier compilé "dist"
    ports:
      - 8080:80  # Rediriger le port 8080 vers le port 80 du conteneur
    restart: always
